### ISSUE TITLE
Upgrade to VS2017 and add .NET Core target

### ISSUE THREAD

**Issue by RLittlesII** [cake-contrib/Cake.Slack#15]
So addin can be loaded from Cake CoreCLR runner

**Comment by RLittlesII** [comment]
@devlead 
I am taking a stab at converting this.  A few things to point out/verify

The following are deprecated and no longer supported .NET 4.6 and above
- NameValueCollection
- WebClient

**Questions**
1. Is there a difference between [WebClient.UploadData](https://github.com/cake-contrib/Cake.Slack/blob/master/src/Cake.Slack/Chat/SlackChatApi.cs#L165) and [WebClient.UploadValues](https://github.com/cake-contrib/Cake.Slack/blob/master/src/Cake.Slack/Chat/SlackChatApi.cs#L222)?  
My thought is they can both just migrate to HttpClient.Post() using StringContent or ByteContent
2. The name value collection is effectively just a JSON representation of a key value pair, this should be easily migrated to a `Dictionary<string,string>` ?

If you'd like to see where I am on the conversion I can submit the PR.  Just wanted to understand any concerns I may be missing. 
Also going to attempt to provide some level of integration script to verify the working product.

**Comment by devlead** [comment]
@RLittlesII cool 👍 

`IDictionary<string,string>` should work yes, only gotcha is that NameValueCollection is case insensitive and can have multiple values per key down now if it matters in this case.
But normally you use `FormUrlEncodedContent` and `IEnumerable<KeyValuePair<string, string>>`.

Difference is that form / json post depends on which endpoint is used.

**Comment by RLittlesII** [comment]
@devlead 
I think that means that one call would need `MultipartFormDataContent` and the other could just post JSON as a string.

**Comment by devlead** [comment]
yip

**Comment by RLittlesII** [comment]
Thanks for getting this merged.  Closing this issue.
