### ISSUE TITLE
Upgrading to .NET Framework 4.6.1

### ISSUE THREAD

**Issue by ayberkcanturk** [cake-contrib/Cake.Slack#17]
Is upgrading .NET Framework 4.6.1 in your roadmap? If yes, may i get the expected date?

**Comment by devlead** [comment]
0.7.0 was released 2 days ago and was 

* Updated to .Net 4.6
* Updated to Cake 0.22.0

https://www.nuget.org/packages/Cake.Slack/0.7.0

Not planning on going 4.6.1 just yet, first on the radar is to add .NET standard 1.6 and have proper framework monikers.

**Comment by ayberkcanturk** [comment]
Thanks
