### ISSUE TITLE
Recommended changes resulting from automated audit

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Slack#23]
We performed an automated audit of your Cake addin and found that it does not follow all the best practices.

We encourage you to make the following modifications:

- [x] You are currently referencing Cake.Core 0.26.0. Please upgrade to 0.28.0
- [x] You are currently referencing Cake.Common 0.26.0. Please upgrade to 0.28.0
- [x] The Cake.Core reference should be private. Specifically, your addin's `.csproj` should have a line similar to this: `<PackageReference Include="Cake.Core" Version="0.28.0" PrivateAssets="All" />`
- [x] The Cake.Common reference should be private. Specifically, your addin's `.csproj` should have a line similar to this: `<PackageReference Include="Cake.Common" Version="0.28.0" PrivateAssets="All" />`
- [x] Your addin should target netstandard2.0. Please note that there is no need to multi-target, netstandard2.0 is sufficient.

Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.org and in the project on github.

**Comment by Jericho** [comment]
We performed a follow up automated audit of your Cake addin and found that some (or all) issues previously identified have not been resolved.

We strongly encourage you to make the modifications previously highlighted.



Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.

This comment was created by a tool: Cake.AddinDiscoverer version 3.12.1

**Comment by gep13** [comment]
Also update iconUrl

**Comment by gep13** [comment]
Also switch to using license expression
